version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  backend:
    restart: on-failure
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: